import 'dart:ui';
import 'package:flutter/material.dart';
import '../../core/app_export.dart';

/// Helper class for managing themes and colors.
class ThemeHelper {
  // The current app theme
  var _appTheme = PrefUtils().getThemeData();

// A map of custom color themes supported by the app
  Map<String, PrimaryColors> _supportedCustomColor = {
    'primary': PrimaryColors()
  };

// A map of color schemes supported by the app
  Map<String, ColorScheme> _supportedColorScheme = {
    'primary': ColorSchemes.primaryColorScheme
  };

  /// Changes the app theme to [_newTheme].
  void changeTheme(String _newTheme) {
    PrefUtils().setThemeData(_newTheme);
    Get.forceAppUpdate();
  }

  /// Returns the primary colors for the current theme.
  PrimaryColors _getThemeColors() {
    //throw exception to notify given theme is not found or not generated by the generator
    if (!_supportedCustomColor.containsKey(_appTheme)) {
      throw Exception(
          "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");
    }
    //return theme from map

    return _supportedCustomColor[_appTheme] ?? PrimaryColors();
  }

  /// Returns the current theme data.
  ThemeData _getThemeData() {
    //throw exception to notify given theme is not found or not generated by the generator
    if (!_supportedColorScheme.containsKey(_appTheme)) {
      throw Exception(
          "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");
    }
    //return theme from map

    var colorScheme =
        _supportedColorScheme[_appTheme] ?? ColorSchemes.primaryColorScheme;
    return ThemeData(
      visualDensity: VisualDensity.standard,
      colorScheme: colorScheme,
      textTheme: TextThemes.textTheme(colorScheme),
      scaffoldBackgroundColor: appTheme.gray50,
      elevatedButtonTheme: ElevatedButtonThemeData(
        style: ElevatedButton.styleFrom(
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(12.h),
          ),
          visualDensity: const VisualDensity(
            vertical: -4,
            horizontal: -4,
          ),
          padding: EdgeInsets.zero,
        ),
      ),
      radioTheme: RadioThemeData(
        fillColor: MaterialStateColor.resolveWith((states) {
          if (states.contains(MaterialState.selected)) {
            return colorScheme.primary;
          }
          return colorScheme.onSurface;
        }),
        visualDensity: const VisualDensity(
          vertical: -4,
          horizontal: -4,
        ),
      ),
      checkboxTheme: CheckboxThemeData(
        fillColor: MaterialStateColor.resolveWith((states) {
          if (states.contains(MaterialState.selected)) {
            return colorScheme.primary;
          }
          return colorScheme.onSurface;
        }),
        side: BorderSide(
          width: 1,
        ),
        visualDensity: const VisualDensity(
          vertical: -4,
          horizontal: -4,
        ),
      ),
      floatingActionButtonTheme: FloatingActionButtonThemeData(
        backgroundColor: colorScheme.onPrimaryContainer,
      ),
      dividerTheme: DividerThemeData(
        thickness: 1,
        space: 1,
        color: appTheme.gray500,
      ),
    );
  }

  /// Returns the primary colors for the current theme.
  PrimaryColors themeColor() => _getThemeColors();

  /// Returns the current theme data.
  ThemeData themeData() => _getThemeData();
}

/// Class containing the supported text theme styles.
class TextThemes {
  static TextTheme textTheme(ColorScheme colorScheme) => TextTheme(
        bodyLarge: TextStyle(
          color: colorScheme.onPrimaryContainer,
          fontSize: 16.fSize,
          fontFamily: 'Cera Pro',
          fontWeight: FontWeight.w400,
        ),
        bodyMedium: TextStyle(
          color: colorScheme.onPrimary,
          fontSize: 14.fSize,
          fontFamily: 'Airbnb Cereal App',
          fontWeight: FontWeight.w400,
        ),
        bodySmall: TextStyle(
          color: colorScheme.onPrimaryContainer,
          fontSize: 12.fSize,
          fontFamily: 'Airbnb Cereal App',
          fontWeight: FontWeight.w400,
        ),
        headlineLarge: TextStyle(
          color: appTheme.whiteA700,
          fontSize: 30.fSize,
          fontFamily: 'Cera Pro',
          fontWeight: FontWeight.w700,
        ),
        headlineSmall: TextStyle(
          color: appTheme.black900,
          fontSize: 24.fSize,
          fontFamily: 'Cera Pro',
          fontWeight: FontWeight.w700,
        ),
        titleLarge: TextStyle(
          color: appTheme.whiteA700,
          fontSize: 20.fSize,
          fontFamily: 'Cera Pro',
          fontWeight: FontWeight.w400,
        ),
      );
}

/// Class containing the supported color schemes.
class ColorSchemes {
  static final primaryColorScheme = ColorScheme.light(
    // Primary colors
    primary: Color(0XFF6FBE5A),
    primaryContainer: Color(0XFF405A93),
    secondary: Color(0XFF405A93),
    secondaryContainer: Color(0XFF130F26),
    tertiary: Color(0XFF405A93),
    tertiaryContainer: Color(0XFF130F26),

    // Background colors
    background: Color(0XFF405A93),

    // Surface colors
    surface: Color(0XFF405A93),
    surfaceTint: Color(0XCC091F41),
    surfaceVariant: Color(0XFF130F26),

    // Error colors
    error: Color(0XCC091F41),
    errorContainer: Color(0XFF397ED0),
    onError: Color(0XFFABAFB3),
    onErrorContainer: Color(0XFF130F26),

    // On colors(text colors)
    onBackground: Color(0XFF0A0A0A),
    onInverseSurface: Color(0XFFABAFB3),
    onPrimary: Color(0XCC091F41),
    onPrimaryContainer: Color(0XFF0A0A0A),
    onSecondary: Color(0XFF0A0A0A),
    onSecondaryContainer: Color(0X4C787878),
    onTertiary: Color(0XFF0A0A0A),
    onTertiaryContainer: Color(0X4C787878),

    // Other colors
    outline: Color(0XCC091F41),
    outlineVariant: Color(0XFF405A93),
    scrim: Color(0XFF405A93),
    shadow: Color(0XCC091F41),

    // Inverse colors
    inversePrimary: Color(0XFF405A93),
    inverseSurface: Color(0XCC091F41),

    // Pending colors
    onSurface: Color(0XFF0A0A0A),
    onSurfaceVariant: Color(0X4C787878),
  );
}

/// Class containing custom colors for a primary theme.
class PrimaryColors {
  // Black
  Color get black900 => Color(0XFF000000);

  // Blue
  Color get blue400 => Color(0XFF48A0EB);
  Color get blue50 => Color(0XFFE7F1FF);

  // BlueGray
  Color get blueGray10033 => Color(0X33D7D7D7);
  Color get blueGray400 => Color(0XFF888888);

  // DeepOrange
  Color get deepOrange50 => Color(0XFFFFDDDD);

  // DeepPurple
  Color get deepPurple50 => Color(0XFFEDDFFE);
  Color get deepPurpleA100 => Color(0XFFA967FD);

  // Gray
  Color get gray200 => Color(0XFFF0F0F0);
  Color get gray300 => Color(0XFFE0E3E6);
  Color get gray30001 => Color(0XFFE1E1E1);
  Color get gray400 => Color(0XFFC4C4C4);
  Color get gray50 => Color(0XFFF8F8FB);
  Color get gray500 => Color(0XFF99879D);

  // Green
  Color get green300 => Color(0XFF85C26F);
  Color get green500 => Color(0XFF5CC73B);

  // LightGreen
  Color get lightGreen600 => Color(0XFF6AC93C);

  // Red
  Color get red400 => Color(0XFFED6461);

  // White
  Color get whiteA700 => Color(0XFFFFFFFF);
}

PrimaryColors get appTheme => ThemeHelper().themeColor();
ThemeData get theme => ThemeHelper().themeData();
